name: Sync to S3
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Ensure this is the latest version supporting Node.js 20

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2  # Ensure this is the latest version supporting Node.js 20
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Sync to S3
      run: aws s3 sync . s3://abstract-classroom-teaching # Change this to your bucket name
